### PR TITLE
implemented environment variable stuff

### PR DESCRIPTION
**Pull request by Anza-BBD**
locally will require a .env file with the below fields. The same environment variables will also have to be set on the server.

DB_USER=*the db user*
DB_HOST=*db url*
DB_DATABASE=*The DB Name*
DB_PASSWORD=*The password*
DB_PORT=*the port*

### CODE REVIEW

**Comment by Michael-Rolle-BBD** [comment]
Can we not set the env vars manually instead of using a .env file? I can only configure them manually on AWS, I can't include a .env file. Also, the db password should be fetched for the prod environment since its managed by secrets manager instead of using an environment variable.

**Review by jennadunfordbbd — APPROVED** [review]
noice

**Comment by Anza-BBD** [comment]
@Michael-Rolle-BBD sure no problem I can hardcode the stuff and pull the password from code.

Will the other team be running their security tests against our aws db, or should they be able to point to a local db when they do their security testing?

Also it's possible to set environment variables from the be deploy pipeline, one of the ways I am sure works is by creating and including a config file in a .ebextensions folder before creating the zip.

**Comment by Michael-Rolle-BBD** [comment]
> @Michael-Rolle-BBD sure no problem I can hardcode the stuff and pull the password from code.
> 
> Will the other team be running their security tests against our aws db, or should they be able to point to a local db when they do their security testing?
> 
> Also it's possible to set environment variables from the be deploy pipeline, one of the ways I am sure works is by creating and including a config file in a .ebextensions folder before creating the zip.

I've already got it setup in tf cloud that we just need to add a variabled which is a map of all the env vars we want and it sets them in the eb environment. Other teams will have to test locally, so we need to look into setting up the db and backend in a docker image at some point.

**Comment by Anza-BBD** [comment]
@Amaxdevq and @Michael-Rolle-BBD  you can choose which one you prefer, this one or https://github.com/Grad-Projects/my-planner/pull/22

**Pull request closed without merging**
